bridges = []

[[instances]]
name = "cc_tuts"
id = "__cc_tuts"
dna_hash = "QmTrHU62m6W4eTeRKic7hHP9faGVHUQtSqiso35w2gYNMX"
uri = "file:dist/cc_tuts.dna.json"

[[UIs]]
name = "CC Tuts"
id = "cc_tuts_ui"
uri = "dir:../gui"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__cc_tuts"
